package com.airbnb.android.showkase.annotation

/**
 * Used to annotate @Composable functions that should be displayed inside the 
 * Showkase browser. Here's how you would use it with your @Composable function:
 * 
 * @ShowkaseComposable(name = "Name", group = "Group")
 * @Composable
 * fun MyComposable() {
 *     .......
 *     .......
 * }
 * 
 * <p>
 * Note: Make sure that you add this annotation to only those functions that don't accept any 
 * parameters. If your function accepts a parameters, wrap it inside another  function that doesn't 
 * accept any parameters. 
 * 
 * For example, here is a @Composable function that requires parameters -
 *
 * @Composable
 * fun MyComposable(name: String) {
 *     .......
 *     .......
 * }
 * 
 * In order to make this function compatible with Showkase, you could further wrap this function 
 * inside a method that doesn't accept a parameters in the following way:
 * 
 * @ShowkaseComposable(name = "Name", group = "Group")
 * @Composable
 * fun MyComposablePreview() {
 *     MyComposable("Name")
 * }
 * 
 * This requirement is even needed by the @Preview functions of Jetpack Compose. 
 * 
 * @param name The name that should be used to describe your `@Composable` function. If you don't
 * pass any value, the name of the composable function is used as the name.
 * @param group The grouping key that will be used to group it with other `@Composable` functions
 * . This is useful for better organization and discoverability of your components. If you don't 
 * pass any value for the group, the name of the class that wraps this function is used as the 
 * group name. If the function is a top level function, the composable is added to a "Default Group".
 * @param widthDp The width that your component will be rendered in inside the Showkase browser. 
 * Use this to restrict the size of your preview inside the Showkase browser.
 * @param heightDp The height that your component will be rendered in inside the Showkase browser.
 * Use this to restrict the size of your preview inside the Showkase browser.
 * @param skip Use this boolean when you want to skip this composable from the Showkase browser. A 
 * use case of this might be when you want a composable that's annotated with @Preview to show previews
 * in Android Studio but don't want to necessary show it in the component browser that's autogenerated
 * by Showkase
 * @param defaultStyle Used to represent a composable function is the default style variant of a given 
 * composable. More information on how Showkase allows you to represent component styles in this section -
 * https://github.com/airbnb/Showkase#representing-component-styles-in-showkase
 *
 */
@MustBeDocumented
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.FUNCTION)
@Repeatable
@Suppress("LongParameterList")
annotation class ShowkaseComposable(
    val name: String = "",
    val group: String = "",
    val styleName: String = "",
    val widthDp: Int = -1,
    val heightDp: Int = -1,
    val skip: Boolean = false,
    val defaultStyle: Boolean = false
) {
    companion object {
        /** The key of the custom compiler plugin argument that customizes the name of the
         * [ShowkaseComposable] annotation, allowing for a custom annotation class that has
         * additional fields or custom field names. The value of this argument is expected
         * to be the fully qualified class name of the annotation
         * (e.g. `com.airbnb.android.showkase.annotation.ShowkaseComposable`). A custom
         * annotation class *must* have the same fields as [ShowkaseComposable], with the
         * exception of [name], [group], and [styleName] if those fields are customized as well.
         */
        const val AnnotationOverride = "showkaseComposableAnnotation"

        /**
         * The key of the custom compiler plugin argument that customized the name of the
         * [ShowkaseComposable.name] field. This can be useful when the [name] of the preview
         * has a different connotation in the scope of a codebase. This requires use of the
         * [AnnotationOverride] to customize the annotation class. It's possible to pass multiple
         * values to this custom field using a `|` delimiter. The first non-empty field will be used.
         */
        const val FieldOverrideName = "showkaseComposableFieldName"

        /**
         * The key of the custom compiler plugin argument that customized the name of the
         * [ShowkaseComposable.group] field. This can be useful when the [group] of the preview
         * has a different connotation in the scope of a codebase. This requires use of the
         * [AnnotationOverride] to customize the annotation class. It's possible to pass multiple
         * values to this custom field using a `|` delimiter. The first non-empty field will be used.
         */
        const val FieldOverrideGroup = "showkaseComposableFieldGroup"

        /**
         * The key of the custom compiler plugin argument that customized the name of the
         * [ShowkaseComposable.styleName] field. This can be useful when the [styleName] of the
         * preview has a different connotation in the scope of a codebase. This requires use of
         * the [AnnotationOverride] to customize the annotation class. It's possible to pass multiple
         * values to this custom field using a `|` delimiter. The first non-empty field will be used.
         */
        const val FieldOverrideStyleName = "showkaseComposableFieldStyleName"
    }
}
