import com.vanniktech.maven.publish.JavaLibrary
import com.vanniktech.maven.publish.JavadocJar

plugins {
    id 'java-library'
    id 'kotlin'
    id 'com.vanniktech.maven.publish'
}

kotlin {
    jvmToolchain(17)
}

//mavenPublishing {
//    configure(new JavaLibrary(new JavadocJar.Javadoc(), true))
//}

publishing {
    repositories {
        maven {
            // The "name" value creates a task like `publishAllPublicationsTo[Name]Repository
            // In this case, publishAllPublicationsToAirbnbArtifactoryRepository
            name = 'airbnbArtifactory'
            url = version.toString().endsWith("SNAPSHOT") ? "https://artifactory.d.musta.ch/artifactory/maven-airbnb-snapshots" : "https://artifactory.d.musta.ch/artifactory/maven-airbnb-releases"
            credentials {
                username = findProperty("ARTIFACTORY_USERNAME")
                password = findProperty("ARTIFACTORY_PASSWORD")
            }
        }
    }
}
